### ISSUE TITLE
Documentation: list sam as a prerequisite.

### ISSUE THREAD

**Issue by mc0e** [aws-samples/s3-to-lambda-patterns#10]
In the [instructions](https://aws.amazon.com/blogs/compute/creating-a-searchable-enterprise-document-repository/) on amazon site, the installation instructions use `sam build` but sam is not listed in the prerequisites just above.

**Comment by mc0e** [comment]
Installation instructions link is https://aws.amazon.com/serverless/sam/

**Comment by jbesw** [comment]
Thanks - I've added a requirements section to the README to address this.
