### ISSUE TITLE
malformed aws.httprequests in indexdocument.js

### ISSUE THREAD

**Issue by patrickthebruce** [aws-samples/s3-to-lambda-patterns#14]
in s3-to-lambda-patterns/decoupled-docrepo/loaders/loadToES/indexDocument.js.

line 30 should read 
`request.headers['host'] =endpoint.host`

when left as process.env.domain, Opensearch requests will fail with dns CERT alt names issue.

**Comment by jbesw** [comment]
Hi Patrick! Thanks for this - I've updated the code accordingly.
