### ISSUE TITLE
How to debug AWS Rekognition in S3-->Step Funcs example?

### ISSUE THREAD

**Issue by weisisheng** [aws-samples/s3-to-lambda-patterns#3]
Everything ran properly but I got no cats to match when using the kaggle "dogs-vs-cats" data subset (10 per group). TIA.

**Comment by jbesw** [comment]
To help debug this, can you post a link to a single image that didn't work, along with the CloudWatch log for the Decider Lambda function. Thanks.

**Comment by jbesw** [comment]
If you run into this again, or have further details, please open a new issue or DM me (@jbesw). Thanks!
