### ISSUE TITLE
Uploading more than 1 file? 

### ISSUE THREAD

**Issue by mattspahr** [aws-samples/s3-to-lambda-patterns#5]
Is it possible to update v2 to handle more than 1 file ? I need to compare 2 files against eachother to come up with json objects that will be added to SQS and forwarded to a DynamoDB table

**Comment by jbesw** [comment]
Hi Matt! Yes, you can open a second S3 object in the code and then compare the two objects to decide which will be added to SQS.

```
        const mySecondObject= await s3.getObject({
          Bucket: record.s3.bucket.name,
          Key: record.s3.object.key
        }).promise()
```

The incoming event is just a JSON object with details of the S3 object that caused the invocation, but inside your code you are free to open any S3 object that the Lambda function has access to.

**Comment by mattspahr** [comment]
this works, thank you. Is there a better way to handle the triggers to the AddToQueueFunction? It seems to me since I am uploading 2 files at once this lambda would be triggered twice @jbesw

**Comment by jbesw** [comment]
Generally, it's best to have one Lambda function invoked per object uploaded to S3. This allows you to focus on the logic that happens for each object in your code, and the Lambda service scales the invocations as needed. 

In terms of your use-case, if I am understanding this correctly, you have 2 files uploaded at a time, with a dependency to access both files in a single Lambda function for comparison. One option to manage this is to use a naming convention with an event notification prefix (https://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html) to invoke only on one file.

For example:
- main_salesdata-12345.csv
- product_salesdata-12345.csv

... I can configure the event source mapping to only fire on a prefix of "main". From the Lambda function, I can open both files if the second file follows a known naming convention.

I hope this helps, but if it's not clear or you have different needs, drop me an email at jbeswick@amazon.com and I'll be happy to discuss further.
