### ISSUE TITLE
How do I find the IAM policy for the parseS3 lambda function?

### ISSUE THREAD

**Issue by weisisheng** [aws-samples/s3-to-lambda-patterns#7]
The policy says "- !Sub 'arn:aws:iam::${AWS::AccountId}:policy/patters-doc-repo'" but I am guessing it is supposed to be "- !Sub 'arn:aws:iam::${AWS::AccountId}:policy/patterns-doc-repo'"

I am getting a rollback unsing the original but my typo fix doesn't work either.  Thanks in advance.

**Comment by jbesw** [comment]
Thanks, this is now fixed - the policy name should be 'arn:aws:iam::${AWS::AccountId}:policy/docrepo-s3-read-policy', which is a managed policy created in the setup template.yaml.

**Comment by weisisheng** [comment]
Thanks very much for the quick response. Now I am back to studying.  All the best, V.
